### ISSUE TITLE
Would it be good to always restart server on file change?

### ISSUE THREAD

**Issue by rnons** [kRITZCREEK/pscid#60] opened 2019-07-22 09:28 UTC
My use case is I have a `module Types` and a `module App`. Module `App` imports module `Types`. 

Usually after making some edits in `Types`, I go to work on `App`. But it seems I have to press `r` in pscid, to be able to use the changes of `Types` in `App`.

Would it be good to always restart server on file change? Or are there other solutions already?

**Comment by kritzcreek** [comment] 2019-07-22 09:35
That doesn't sound right... after you made changes in `Types` the ide server should know about them. It won't display errors in `App` right away, but as soon as you make a change in `App` and save the file you should be seeing errors.

("That doesn't sounds right" meaning "There might be a bug here" not your report being wrong)

**Comment by rnons** [comment] 2019-07-22 12:55
I made a reproducible repo at https://github.com/rnons/pscid-issue-60. Please see if you can reproduce.
Sometimes I need to repeat a few times to reproduce.

**Comment by kritzcreek** [comment] 2019-07-24 11:21
Thank you for the repo! Work has been pretty busy so I didn't get to it yet, I hope I can find some time this evening.

**Comment by rnons** [comment] 2019-07-24 12:57
No worry, it doesn't block me. I modified pscid locally to reset after file change.

**Comment by ssadler** [comment] 2019-10-22 19:40
I might be having a similar issue. After changing exports in one module, another module doesn't see them until I restart pscid. Also, when I save a module, it type checks, but modules that depend on it are not type checked. I'm guessing that neither of these are the intended behaviors?

**Comment by piq9117** [comment] 2020-03-16 16:31
@ssadler You probably already know the answer to this but just in case, I asked about this in fp-chat which helped me clear some confusion.
> yeah, purs ide only builds one file at a time - it's something to be aware of if using any kind of hot loading/auto reloading thing too, as you'll probably want to stop the watcher and do a "proper" build once in a while (or if you know you've made a change that will break things in other modules). It's so ingrained for me now that I forget that it's even an oddity :smile:.
Christoph has been experimenting with something that might be able to preserve the current speed while still being able to handle dependent modules properly but it's not close to being something the rest of us can play with yet, afaik. - @garyb 

What I've been doing is using the full build option. Pressing `b` in the terminal where pscid is running.

**Comment by kritzcreek** [comment] 2020-05-29 09:15
I'm going to say that this should be fixed with PureScript 0.13.8 or later. If you're still experiencing these kind of issues please feel free to open a new issue.

**Closed as completed by kritzcreek** 2020-05-29 09:15 UTC
